### ISSUE TITLE
Add support for client JSON feature

### ISSUE THREAD

**Issue by plannigan** [plannigan/ktor-moshi#4]
This issue is for tracking progress to the new capabilities.

- [x] Client serialization implementation with tests (#30)
- [x] Build dedicated client package (#32)
- [x] Extract common `gradle` functionality (#31)
- [x] Rename server directory (#37 )
- [x] Publish both server and client package from CI (#33)
